### ISSUE TITLE
Error processing project file: ..

### ISSUE THREAD

**Issue by sysads** [manateelazycat/deepin-voice-recorder#5]
Hi

I tried installing on Ubuntu 16.04 but gets the following error when i run qmake ..

Error processing project file: ..

Any way to fix this?

**Comment by liu-xiao-guo** [comment]
I in fact successfully compiled it on 16.04. Did you compile and install deepin-tool-kit?

**Comment by sysads** [comment]
No I could not. Can you share the steps? Thanks

**Comment by manateelazycat** [comment]
All deepin apps depend deepin-tool-kit, please compile deepin-tool-kit first

**Comment by sysads** [comment]
Closed ticket but no solution :(

**Comment by sysads** [comment]
so how do you compile deepin-tool-kit
